import Head from "next/head";
import { Inter } from "next/font/google";
import { NextPage } from "next";
import Header from "@/components/Header";
import Search from "@/components/Search";
import Footer from "@/components/Footer";
import SearchResults from "@/components/SearchResults";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import axios from "axios";
const inter = Inter({ subsets: ["latin"] });


export default function Home() {
  return (
    <>
      <Head>
        <title>Tìm Bác sĩ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Search />
        <Footer />
      </main>
    </>
  );
}


